import '../models/transaction_model.dart';

class MockDataGenerator {
  static List<TransactionModel> getInitialTransactions() {
    final now = DateTime.now();

    return [
      TransactionModel(
        id: 'TXN-2026-001',
        date: now.subtract(const Duration(days: 1)),
        category: 'Flights & Air Tickets',
        description: 'Emirates Roundtrip Air Tickets for Commissioning Engineers',
        amountEgp: 0.0,
        amountEur: 1850.00,
        amountUsd: 0.0,
        invoiceNumber: 'INV-DXB-9982',
        responsiblePerson: 'BS (Bishoy S.)',
        projectTag: 'Siemens UAE Automation',
        sourceAccount: 'CIB-EUR',
        type: TransactionType.expense,
      ),
      TransactionModel(
        id: 'TXN-2026-002',
        date: now.subtract(const Duration(days: 2)),
        category: 'Workshop Expenses',
        description: 'Purchase of Schneider Electric MCC panels & terminal blocks',
        amountEgp: 145000.00,
        amountEur: 0.0,
        amountUsd: 0.0,
        invoiceNumber: 'INV-EGY-4431',
        responsiblePerson: 'MR (Mena R.)',
        projectTag: 'SCC - ABB Contactor Upgrade',
        sourceAccount: 'CIB-EGP',
        type: TransactionType.expense,
      ),
      TransactionModel(
        id: 'TXN-2026-003',
        date: now.subtract(const Duration(days: 3)),
        category: 'Visas & Travel Docs',
        description: 'Business Entry Visa Processing for Senegal Site Team',
        amountEgp: 18500.00,
        amountEur: 0.0,
        amountUsd: 420.00,
        invoiceNumber: 'INV-SN-1029',
        responsiblePerson: 'ES (Eng. Sameh)',
        projectTag: 'FCB Senegal Cement Plant',
        sourceAccount: 'CIB-USD',
        type: TransactionType.expense,
      ),
      TransactionModel(
        id: 'TXN-2026-004',
        date: now.subtract(const Duration(days: 4)),
        category: 'Salaries & Wages',
        description: 'Monthly Senior Control Systems Engineers Payroll Settlement',
        amountEgp: 480000.00,
        amountEur: 0.0,
        amountUsd: 0.0,
        invoiceNumber: 'PAY-2026-07',
        responsiblePerson: 'Finance Dept',
        projectTag: 'General HQ / Internal Overhead',
        sourceAccount: 'QNB-EGP',
        type: TransactionType.expense,
      ),
      TransactionModel(
        id: 'TXN-2026-005',
        date: now.subtract(const Duration(days: 5)),
        category: 'Daily & Site Allowances',
        description: 'Per Diem site allowance for EWEKORO PCS commissioning team',
        amountEgp: 0.0,
        amountEur: 0.0,
        amountUsd: 2600.00,
        invoiceNumber: 'ALLW-NG-008',
        responsiblePerson: 'MF (Eng. Mostafa)',
        projectTag: 'EWEKORO PCS Upgrade',
        sourceAccount: 'BS',
        type: TransactionType.expense,
      ),
      TransactionModel(
        id: 'TXN-2026-006',
        date: now.subtract(const Duration(days: 6)),
        category: 'Hotel & Accommodation',
        description: 'Jubail Crown Plaza Hotel Booking for 14 nights',
        amountEgp: 0.0,
        amountEur: 0.0,
        amountUsd: 3100.00,
        invoiceNumber: 'HOTEL-KSA-77',
        responsiblePerson: 'AH (Ahmed H.)',
        projectTag: 'Jubail PCS Upgrade',
        sourceAccount: 'CIB-USD',
        type: TransactionType.expense,
      ),
      TransactionModel(
        id: 'TXN-2026-007',
        date: now.subtract(const Duration(days: 7)),
        category: 'Surveys & Engineering Audits',
        description: 'Pre-commissioning site audit report advance payment',
        amountEgp: 95000.00,
        amountEur: 0.0,
        amountUsd: 0.0,
        invoiceNumber: 'INV-AUD-302',
        responsiblePerson: 'MR (Mena R.)',
        projectTag: 'Sinai Engineering Expansion',
        sourceAccount: 'CASH-VAULT',
        type: TransactionType.expense,
      ),
      TransactionModel(
        id: 'TXN-2026-008',
        date: now.subtract(const Duration(days: 8)),
        category: 'Office Rent',
        description: 'HQ Office Space Monthly Lease Payment',
        amountEgp: 65000.00,
        amountEur: 0.0,
        amountUsd: 0.0,
        invoiceNumber: 'RENT-2026-07',
        responsiblePerson: 'Office Admin',
        projectTag: 'General HQ / Internal Overhead',
        sourceAccount: 'CIB-EGP',
        type: TransactionType.expense,
      ),
      TransactionModel(
        id: 'TXN-2026-009',
        date: now.subtract(const Duration(days: 9)),
        category: 'Material & Freight Shipping',
        description: 'DHL Express Siemens S7-1500 PLC Spare Modules freight',
        amountEgp: 22000.00,
        amountEur: 750.00,
        amountUsd: 0.0,
        invoiceNumber: 'DHL-8839102',
        responsiblePerson: 'BS (Bishoy S.)',
        projectTag: 'Slag Mill KSA Drive Integration',
        sourceAccount: 'CIB-EUR',
        type: TransactionType.expense,
      ),
      TransactionModel(
        id: 'TXN-2026-010',
        date: now.subtract(const Duration(days: 10)),
        category: 'Client Dinners & Meetings',
        description: 'Arabian Cement Management Kickoff Dinner',
        amountEgp: 14200.00,
        amountEur: 0.0,
        amountUsd: 0.0,
        invoiceNumber: 'DIN-901',
        responsiblePerson: 'ES (Eng. Sameh)',
        projectTag: 'Silo Arabian Cement Commissioning',
        sourceAccount: 'MR',
        type: TransactionType.expense,
      ),
    ];
  }
}
