import '../models/payroll_model.dart';

class PayrollSeed {
  static List<PayrollModel> getInitialPayroll() {
    final now = DateTime.now();

    return [
      PayrollModel(
        id: 'PAY-2026-0801',
        employeeName: 'Eng. Emad',
        jobTitle: 'Chief Executive & Lead Automation Architect',
        department: 'Executive Management',
        payPeriod: 'August 2026',
        payDate: DateTime(now.year, now.month, 1),
        currency: 'EGP',
        baseSalary: 120000.0,
        siteAllowance: 15000.0,
        bonus: 10000.0,
        taxDeduction: 14000.0,
        insuranceDeduction: 3000.0,
        paymentAccount: 'CIB-EGP',
        status: PayrollStatus.paid,
        notes: 'Monthly executive leadership salary package',
      ),
      PayrollModel(
        id: 'PAY-2026-0802',
        employeeName: 'Eng. Mostafa',
        jobTitle: 'Senior Systems Integration Engineer',
        department: 'Control Systems',
        payPeriod: 'August 2026',
        payDate: DateTime(now.year, now.month, 1),
        currency: 'EGP',
        baseSalary: 65000.0,
        siteAllowance: 8500.0,
        bonus: 5000.0,
        taxDeduction: 6800.0,
        insuranceDeduction: 2200.0,
        advanceDeduction: 5000.0,
        paymentAccount: 'CIB-EGP',
        status: PayrollStatus.paid,
        notes: 'Includes Jubail site allowance and partial cash advance deduction',
      ),
      PayrollModel(
        id: 'PAY-2026-0803',
        employeeName: 'Eng. Badawy',
        jobTitle: 'Lead Electrical & Commissioning Engineer',
        department: 'Power & Drives',
        payPeriod: 'August 2026',
        payDate: DateTime(now.year, now.month, 1),
        currency: 'EUR',
        baseSalary: 4500.0,
        siteAllowance: 650.0,
        bonus: 400.0,
        taxDeduction: 500.0,
        insuranceDeduction: 200.0,
        paymentAccount: 'CIB-EUR',
        status: PayrollStatus.paid,
        notes: 'Senegal project overseas commissioning payroll in EUR',
      ),
      PayrollModel(
        id: 'PAY-2026-0804',
        employeeName: 'Hanafy',
        jobTitle: 'Senior Mechanical & Workshop Technician',
        department: 'Workshop & Fabrication',
        payPeriod: 'August 2026',
        payDate: DateTime(now.year, now.month, 1),
        currency: 'EGP',
        baseSalary: 32000.0,
        siteAllowance: 3500.0,
        bonus: 2000.0,
        taxDeduction: 2800.0,
        insuranceDeduction: 1200.0,
        paymentAccount: 'CIB-EGP',
        status: PayrollStatus.paid,
        notes: 'Monthly workshop team payroll',
      ),
      PayrollModel(
        id: 'PAY-2026-0805',
        employeeName: 'BS (Bishoy S.)',
        jobTitle: 'SCADA & PLC Software Engineer',
        department: 'Software & Automation',
        payPeriod: 'August 2026',
        payDate: DateTime(now.year, now.month, 1),
        currency: 'EGP',
        baseSalary: 48000.0,
        siteAllowance: 5000.0,
        bonus: 3000.0,
        taxDeduction: 4500.0,
        insuranceDeduction: 1800.0,
        paymentAccount: 'CIB-EGP',
        status: PayrollStatus.paid,
        notes: 'Monthly engineering payroll',
      ),
      PayrollModel(
        id: 'PAY-2026-0806',
        employeeName: 'MR (Mena R.)',
        jobTitle: 'Electrical Panel Design Engineer',
        department: 'Hardware & Design',
        payPeriod: 'August 2026',
        payDate: DateTime(now.year, now.month, 1),
        currency: 'EGP',
        baseSalary: 45000.0,
        siteAllowance: 4000.0,
        bonus: 2500.0,
        taxDeduction: 4200.0,
        insuranceDeduction: 1600.0,
        paymentAccount: 'CIB-EGP',
        status: PayrollStatus.paid,
        notes: 'Monthly engineering payroll',
      ),
    ];
  }
}
